release-engineering/ubi-population-tool

tests/test_pulp.py, ubipop/_pulp.py
For cdn and rsync distributors set
override config wiht delete=True
=> Publish with delete=True on certain distributors

tests/test_cli.py, tests/test_ubipop.py, ubipop/__init__.py, ubipop/cli.py
Added functionality for outputting repo ids of changed repos
to file.
Available via new cli option
=> Output changed repos to file

tests/test_utils.py, ubipop/_utils.py
Fixed  wrongly ordered variables the were returned from get_action() method
=> Pulp action param order

tests/test_ubipop.py, ubipop/__init__.py
Swap dst and src repo in creation of association object.
Improved unit test in this context.
=> Fix creation of association object

ubipop/__init__.py, ubipop/_pulp_client.py, ubipop/_utils.py, ubipop/cli.py
useless-object-inheritance and inconsistent-return-statements are not
fixed.
=> Fix pylint issues

setup.py
Include commits up to 5906d68f7d1d8f13bc5448a83ff4968716954059
=> Release version 0.1.13

setup.py
commit id: 7203a3cb7525b4729b8c49d521511aa6837a9ff7
=> Revert commit Release version 0.1.13

tests/integration/data/associate-md.yaml, tests/integration/data/clean-repos.yaml, tests/integration/test_association.py
Integration tests were failing due:
- New validation in ubi-config
- Issue #93
This fix #93.
=> Fix integration tests

tests/test_pulp.py
The issue was introduced in this urllib3 PR:
https://github.com/urllib3/urllib3/pull/1652/files#diff-b24c3b9dfb0ce4d1adcc7a9a689877beR507
Fixes #134
=> Fix Pulp client retry tests for urllib3 > 1.25.3

ubipop/_pulp_client.py
(UBIPOP_HTTP_TIMEOUT): New env variable added.
(do_request): append "timeout" argument.
=> Set custom timeout for requests [RHELDST-554]

tests/test_matcher.py, ubipop/_matcher.py
Previously the method _get_rpm_output_set() stripped away
all modular packages and kept only the latest version of packages.
This seems to be too strict for source RPMs in some edge cases, at the
time when source RPMs output set is created - because the output set is
based on final output sets of binary and debug rpms that are already properly
filtered - they include only the latest versions of RPMs and non-modular
packages. Because of that we don't need to check again if the source RPM is
modular or not, or keep the latest version of SRPM. Only blacklisting
should happen. There are some edge cases when the original implementation
stripped some source RPMs that should be part of the output set. It's
probable that the edge cases happen due to data inconsistency especially
for modular …
=> Fix creation of source RPMs output set

tests/test_ubipop.py, ubipop/__init__.py
Previously ubipop waited for each triplet of repos
(binary, debug, source) that were currently
in processing until publication of those repos
is finished. Only after publication finished,
ubipop was allowed to start processing another triplet.
As repo triplet is independent from other ones, it's
not required to do this in blocking way. So now
publication of repos is triggered at the same time
as before but waiting for all to finish is moved to
end of ubipop processing.
=> Make publication of repos non-blocking [RHELDST-6394]

tests/test_matcher.py
Fixed couple of tests due to changes in pubtols-pulplib.
=> Tests fix [RHELDST-8723]

.pre-commit-config.yaml, ubipop/__init__.py
Manifests for SRPM and debug repos were switched accidentally,
let's fix that now.
=> Fix getting ubi-manifests [RHELDST-8706]

tests/integration/data/ubi7/expected_rhel7_repo.json, tests/integration/test_association.py
1.use the manifest to do the ubipop
2.use the gitlab as the config url
3.add some validation for the check
4.add the expected json result
5.add one test case only, the next will be added later
=> Refactor the ubipop test cases

requirements.txt, tests/test_ubipop.py, ubipop/__init__.py, ubipop/cli.py
Added cache purge for mutable urls of ubi repositories
using fastpurge client.
=> Add cache purging [RHELDST-12390]

ubipop/cli.py
For CLI this change enables logging of ubi-config on INFO level.
=> Enable logging of ubi-config [RHELDST-6398]

tests/test_pulp.py, ubipop/_pulp_client.py
1.add method to make log for associate and unassociate more readable
2.add the unit test for testing the unassocate module default log
3.add the unit test for testing the associate package log
=> Improve the log of associate and unassociate [RHELDST-9945]

ubipop/_cdn.py
Previously CDN or Fastpurge client were instatiated even if there was not enough configuration provided for them.
Also the edgerc conf. file was required everytime even if we didn't want to use cache purging functionality.
Let's now fix that so we get clients only if at least some minimal configuration is provided.
=> Fix CDN and Fastpurge client handling

.github/workflows/tox-test.yml, tox.ini
Added SAST check for this repository.
=> Add bandit SAST check [RHELDST-18795]

tests/integration/test_association.py
1.let pub client to do the publish
=> Add the command to let pub client to do the publish [RHELDST-25071]

tox.ini
1.add UBIPOP_SKIP_PUBLISH and PUB_CONFIG_FILE
=> Add the skip publish and pub config environment

.pre-commit-config.yaml, tests/conftest.py, tests/test_cli.py, tests/test_matcher.py, tests/test_ubi_manifest_client.py, ubipop/_matcher.py, ubipop/cli.py, ubipop/ubi_manifest_client/client.py
* auto-updates from black/isort via pre-commit ci
=> Upgrade CI

poetry.lock, pyproject.toml, ubipop/cli.py
* removed unused deps for tool and tests
* removed setup of foreign logger of fastpurge
=> Remove unused deps
