ubipop/cli.py

Merely importing a module shouldn't have the side-effect of changing
the global logging config, which can only be done once per process.
It's fragile and could lead to confusing behavior where log format
differs depending on the order of imports.
Since this is only intended to enable output for the CLI, let's
move it within the CLI's main method.

Call logging.basicConfig only within main

---

README.md

The command and some argument names were incorrect.

Fix command name and arguments in README

---

README.md
docs/index.rst
setup.py

The API is too unstable at the moment and likely needs some
significant revision before we could commit to supporting that.
Let's rebrand this project as only a CLI tool for now, until we
have time to revise the API (probably meaning until we're ready
to actually *use* the API from outside of the tool).
Fixes #9

Remove public API for now

---

tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_utils.py

This PR is a refactor of creation of units that should associated and unassociated where I added more abstraction which should result better readability and maintainability. 
Renamed **out_repo_set** attr to **repos**, of UbiPopulateRunner class. I found it too long.
Also added tests to improve code coverage.

Refactor associations and unassociations, add test coverage, renamed some attributes

---

tests/test_cli.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/cli.py

New cli option intriduced --output-all-repos.
If provided along with --output-changed-repos, it will
write to output file all output repos.

Add option to write all output repos to file

---

tests/test_ubipop.py
ubipop/__init__.py

Reworked srpms output set creation. Now it doesn't guess filename of srpm if its filename is not referenced on binary rpm unit.
Updated tests.

Rework srpms output set creation

---

ubipop/_pulp_client.py

type_id must be passed as tuple to associate function in pulp_client module

Fix passing modulemd type_id to associate function

---

tests/integration/data/associate-md.yaml
tests/integration/data/associate-pkg.yaml
tests/integration/data/clean-repos.yaml
tests/integration/data/do-not-associate-excluded-pkg.yaml
tests/integration/data/do-not-associate-pkg-if-in-exclude.yaml
tests/integration/data/do-not-associate-pkg-if-not-in-include.yaml
tests/integration/test_association.py
tox.ini

Add integration tests that will be responsible for evaluating if ubi-pop can perform operations as expected.
Tests include package and modules operations. Each test has a short description responsible for explaining what the test should do.

Add integration tests.

---

tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_pulp_client.py
ubipop/_utils.py

If there modulemd_defaults for specific modulemd in the same repo,
then it should be copied to the ubi repos.
Ubipop now looks for modulemd_defaults units after searching modulemd
units with the same name and stream. If there's any, add it to push
queue.
This fixes #56

Copy modulemd_defaults units as well while populating ubi repos

---

tests/test_pulp.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_pulp_client.py

Blacklist is not applied for pkgs from modules.
This change also includes also reworked finalizing
output pkgs set - do not include modular package
which is not referenced by any module.
Fixes #55

Do not blacklist pkgs from modules

---

ubipop/_pulp_client.py

While searching the existing modulemd_defaults units in a repo, in
order to get all the units, we don't pass name stream arguments to
search_module_defaults method, so, it should allow these arguments
to be None

pulp search_module_defaults should allow name and stream is None

---

requirements.txt
tests/test_ubipop.py
ubipop/_pulp_client.py

Previously used rpm-vercmp was unreliable for
some variants of version, so this commit
moves to cmp_version python package which
is more reliable.
Fix #66 .

Use cmp_version package for version comparison

---

tests/test_ubipop.py
ubipop/__init__.py

This change will allow to have pkgs with different arches
in one output repo.
Previously it took only the latest pkg and arch
wasn't taken into account.
Also added test and updated releated one.
Fixes  #68

Allow multi arch pkgs in one repo

---

tests/test_pulp.py
ubipop/_pulp_client.py

To make sure tool process isn't interrupted due network issues,
retry mechanism based on urllib3 Retry was implemented.
New configuration environment variables to customize this
were added:
- UBIPOP_HTTP_TOTAL_RETRIES
- UBIPOP_HTTP_RETRY_BACKOFF
fixes #32

Added requests retry mechanism for all requests call in _pulp_client

---

tests/test_ubipop.py
ubipop/__init__.py
ubipop/_pulp_client.py

Previously, 'profiles' was the key part to get the right modulemd_defaults
units to associate and unassociate. However, as the keyword in profiles
always include speical character '.'(dot), it leads to mongodb query failure.
Since while assmbling the lists of md_defaults_assoc and md_defaults_unassoc,
the 'profiles' has already been considered, we don't have to re-query with
it, but, because association and unassociation happens at the same time in
threads, it could delete the new unit if association happens before unassociation,
so, we serialize the modulemd_defaults units unassociation and association.

Get rid of 'profiles' in module_defaults association

---

tests/test_ubipop.py
ubipop/__init__.py

Now since the modulemd_defaults units association and unassociation
actions are being done separately and _associate_unassociate_units
method only takes iterable as input, we need to make them iterable
first.

Fix type error.

---

tests/data/ubiconf_golang.yaml
tests/test_ubipop.py
ubipop/__init__.py

Packages for modules are included based on the package name present in
the repositories module profiles. This leads to missing packages in the
output repositories, as not every package required is included in module
profiles.
In this change, if no module profile is defined in the UBI
configuration, include every package present in the module artifacts.
Fix #81

Include all module packages if no profile is defined

---

tests/test_ubipop.py
ubipop/__init__.py
ubipop/_pulp_client.py

is_modular adn sourcerpm_filename are keyword arguments, therefore
they should be as well passed as keyword arguments

Fixed inconsistency in Package initializations

---

tests/test_pulp.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_pulp_client.py

This commit includes more precise handling
of modular packages. Every rpm is checked againts
pulp if it exists in binary rpm or debug rpm repo
and then rpm is added accordingly.
This leads to correct assocications of debug rpms
and also correct references for source rpms
of modular packages.
Also fixed overlapping package names in profiles
which won't duplicated now.
Fixes #24 #52  #27

Reworked matching modular rpms

---

tests/integration/test_association.py
tests/test_cli.py
tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_pulp_client.py
ubipop/_utils.py
ubipop/cli.py

- Fixed code styling
- Fixed most pylint issues

Fix linter issues

---

tests/test_cli.py
tests/test_pulp.py
tests/test_ubipop.py
tox.ini

Tests should also be linted by pylint
because it's also part of the library.
Docs could also be added but I felt that this
does not belong to the library codebase.

Include test code in linter.

---

tests/test_pulp.py
ubipop/_pulp_client.py

With this the session won't be shared across
multiple threads.
This fix #57.

Use threading.local to store session

---

requirements.txt
test-requirements.txt

- Correct library names are ubi-config, more-executors (i.e. '-'
and not '_'). During pip install, the names are normalized so this
doesn't make a difference, but it does break some other tools
such as https://libraries.io/pypi/ubi-population-tool.
- There's no need to repeat same dependency in test-requirements.txt
and requirements.txt
- There's no need to repeat a transitive dependency (futures) as
a direct dependency in requirements.txt

Fix minor issues in requirements

---

tests/test_ubipop.py
ubipop/__init__.py
ubipop/_pulp_client.py

This change introduces custom calculation
of is_modular field of rpm unit. This field
is not taken from pulp unit metadata anymore because
it is unreliable.
is_modular field is true in case package comes from
artifacts of modulemd directly or is referenced
by any modulemd artifacts in input repository.
Fixes #94

Custom calculation of is_modular field

---

tests/test_ubipop.py
ubipop/__init__.py

Previously when we got more modules with the same
name, stream and version, it was undefined which one
goes to output ubi repo. It may have resulted into failed
dependency check during installation of packages.
Now in these cases we take all modules that differs only context
but the same name:stream:version.
Fixes #100

Keep all mds with same name:stream:version

---

tests/test_ubipop.py
ubipop/__init__.py

Since there's no blacklist for modules, excluded source RPMs referenced
by modular RPMs are no longer added to the blacklist. Fixes #97.

Don't blacklist source RPMs referenced by modules

---

.travis.yml
requirements.txt
tests/test_ubipop.py
ubipop/_pulp_client.py

This change replaces buggy cmp_version package
with python bindings of official rpm project.
This should ensure that ubipop will sort rpms by correctly implemented and maitained vercmp algorithm.
Fixes #104

Replace cmp_version with rpm python bindings

---

.travis.yml

This change explicitly sets dist in travis
to 'trusty' for py26 env.
The reason is that 'xenial' was made default dist on travis
recently and it does not support python 2.6 anymore.

Explicit dist: trusty in travis.yml for py26 env

---

requirements.txt
setup.py

This commit adds conditional creation of install_requires list
in setup.py for rpm distribution.
If rpm-py-installer was added there unconditionally,
rpm of ubipop couldn't be installed on some envs.
If implemented this way there is no need to change
anything in .spec file for rpm builds.
This fix is based on rpm-py-installer docs:
See Q6 in FAQ ->
https://github.com/junaruga/rpm-py-installer/blob/master/docs/users_guide.md

Conditional creation of install_requires of rpm distribution

---

tests/test_pulp.py
ubipop/_pulp_client.py

When insecure=True is pass to Pulp client instance it's expected that
ssl certificate can't be verified, therefore it's not neccessary to
keep SSL warning messages enabled.

When insecure=True disable SSL warnings logging

---

tests/test_ubipop.py
ubipop/__init__.py

When making list of srpm packages, there are duplicates in output
list due fact that many rpms can share one srpm. That leads to
unnecessary duplicated associations.
That was fixed in this commit

Remove duplicate associations for srpm packages (#74)

---

tests/test_ubipop.py
ubipop/__init__.py

release and version subkeys were added to srpm unique filter to work
correctly in situations where srpms with same name but different
versions or releases needs to be associated.

Fix unique filter for srpms

---

tests/test_ubipop.py
ubipop/__init__.py

In keep_n_latest_packages(), keep track of filenames for packages added from modules and skip them while processing packages from white list.
Add test to ensure that only package from modules is kept.
Refactor keep_n_latest_packages():
- Move filter per arches of non-modular to the main packages loop
- Use collections.deque as queue to keep n package versions per arch
- Build set of package filenames from modules for reference checks outside the main packages loop.
- Extend doc string
Fixes #105

Avoid duplicates for packages present in modules and white list

---

tests/test_ubipop.py
ubipop/__init__.py

Avoid duplicated modular packages in output package list when there are
duplicated modular packages in the input package list.
Fixes #105

De-duplicate modular packages from input packages

---

CHANGELOG.md
tests/test_cli.py
tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_pulp_client.py
ubipop/cli.py

UbiPopulate now accepts specific content set lables and/or repository
IDs for content calculation.
Fixes #121

Enable population by content set(s) or repo ID(s)

---

tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_pulp_client.py

Using the new repo note, ubi_population, this commit ensures repo sets
that would contain repos not intended for population are skipped.
Fixes #92

Only populate repos marked for population

---

ubipop/__init__.py

This commit fixes a previously implemented log message for skipped
repo sets, where UBI content sets were logged instead of repos. This
should better describe what's being skipped, as multiple repos can
share a content set label.

Correct log message for skipped UBI content sets [DELIVERY-6938]

---

tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_pulp_client.py
ubipop/_utils.py

This change adds support for ubi repositories population
from more that one input repo.
Repo note 'population_sources' is here used for
getting sources, if it's not available, fallback
to manual finding of input repositories.
This change also refactors usage of 'ubi_population' repo note
that enables population of given ubi repositories

Supp population sources

---

tests/test_ubipop.py

There was an attempt to disable a few warnings by comments, but that
wasn't working. It seems that pylint's behavior regarding multi-line
statements might have changed since the code was introduced.
Moving the comment prior to the statement works, so do that.

ci: fix pylint failures

---

tests/test_ubipop.py
ubipop/__init__.py

This fixes a situation when modular packages are selected for output set
of ubi repo but they shouldn't be there because respective modulemd unit
is not selected as a content of ubi repo.
This lead to situations when a repo contained modular rpm from a
modulemd that wasn't associated with repo. This is wrong and could lead
to problems with packages installation from ubi repos.

Fix association of unwanted modular rpms [RHELDST-6453]

---

requirements.txt
tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_pulp_client.py
ubipop/_utils.py

- Started using Client and YumRepository from pubtools.pulplib.
- It's still required to use to old client located in this repository
until all interaction with pulp is refactored with pulplib.
- Getting ubi repo sets is now way easier with the latest updates in
pulplib - we can directly ask for related source and debug repository
- Using only population_source repository attr., since it's populated
for all ubi repositories
- Removed already unused code and updated tests
- Moved any expensive and difficult to mock calculations out of
UbiPopulate.__init__()

Refactored with pubtools.pulplib.YumRepository

---

tests/test_matcher.py
tests/test_pulp.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_matcher.py
ubipop/_pulp_client.py

This commit starts decoupling of big blob of code inside UbiPopulateRunner
class that did almost everything.
Methods for getting modulemd units and modular rpms and srpms was moved away
from this class to *Matcher class. It provides convenient methods for
searching in pulp and also encapsulates functionality of creation of
output sets of units for ubi repositories.
It was written in a way that is completely asynchronous and can be
easily extended with methods for matching e.g. non-modular units.
Currently ubipop is in hybrid state where two pulp clients are used
one from ubipop and the other from pubtools.pulplib. This makes
especially writing tests quite inconvenient.

Make matching modules and modular rpms efficient [RHELDST-6391]

---

ubipop/__init__.py

Previously ubipop requested repository from pulp
in every iteration in _create_srpms_output_set method.
Let's save the repository into dict in order not to do
unnecesary requests to pulp.

Optimize requests for repository

---

tests/test_matcher.py
ubipop/_matcher.py

When ubi-config requests a profile from modulemd but
the profile is not in the modulemd, ubipop previously failed
with KeyError.
Now missing profile is not treated as a fatal error.

Fix KeyError when profile is missing in modulemd

---

ubipop/__init__.py

One of output repository object was stored as YumRepository which wasn't
desirable because other code expects this to be Future.
Let's make this consistent now have all repositories stores as futures.

Fix futures consistency in output repositories [RHELDST-6391]

---

tests/test_matcher.py

Fixes test that relied on ordering after calling
_keep_n_latest_rpms(). When using more arches
in rpms, kept latest rpms might be in random order
which is perfectly fine for ubipop. So let's make
the test test_keep_n_latest_rpms_multiple_arches()
stable.
Also adding and fixing a bunch of comment in tests.

Fix unstable test

---

tests/test_cli.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/cli.py

Added support for matching correct ubi-config item by
major version and/or by content set regex.
Features are enabled also for CLI.

Matching ubi-config by major version or content set regex [RHELDST-6396]

---

tests/test_matcher.py
tests/test_pulp.py
tests/test_ubipop.py
tests/test_utils.py
ubipop/__init__.py
ubipop/_matcher.py
ubipop/_pulp_client.py
ubipop/_utils.py

Matching modulemd_defaults units for ubi repos population is now
reworked and uses Client from pubtools-pulplib in the similar way
as matching other units (modulemd, rpm ...) works.

Rework matching modulemd_defaults units [RHELDST-6393]

---

requirements.txt
tests/conftest.py
tests/test_matcher.py
tests/test_pulp.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_matcher.py
ubipop/_pulp_client.py

This comming includes refactoring of getting current content
of ubi repositories.
- Queries for getting content from ubi repos now re-uses code from
Matcher class. Some private methods were made public and changed to
class methods.
- All related queries located originally located in _pulp_client.py
were removed also with model classes. It brings us closer to
100% usage of pubtools-pulplib Client. Currently we still need to use
only calls from _pulp_client.py for content un/association that are
not ready in pubtools-pulplib at the time of creation of this commit.
- Added couple of helper methods for test and updated/add tests

Refactored getting current content from ubi repos

---

tests/test_ubipop.py
ubipop/__init__.py

Check if ubi_config_version note info exists before calling _get_config(),
so it will not crash when ubi_config_version is empty.
And an ERROR level logger added.

ubipop indicate user populating a repo without ubi_config_version [RHELDST-8053]

---

tests/test_ubipop.py
tox.ini

Codecov action to upload coverage report was upgraded to v2.
However, the reports were not uploaded correctly as v2 accepts
coverage reports in xml format only. Hence, updating the cov
job in tox to generate coverage reports in xml instead of html.

Update tox cov job to generate xml coverage report

---

.github/CODEOWNERS

As the ubi-population-tool finally finds new owners,
I am nominating new code owners for this project.

New codeowners [RHELDST-6549]

---

.pylintrc
requirements-dev.txt
tests/conftest.py
tests/test_cli.py
tests/test_pulp.py
tests/test_ubi_manifest_client.py
tests/test_ubipop.py
tox.ini
ubipop/__init__.py
ubipop/cli.py
ubipop/ubi_manifest_client/client.py
ubipop/ubi_manifest_client/models.py

This change introduces uasge of ubi-manifest that provides
manifests of final content of ubi repos. Following
is included in this changed:
* implemented a simple client for ubi-manifest servivce with task poller
* integrated usage of ubi-manifests in the ubipop workflow
* added required cli option --ubi-manifest-url
* tests were updated
There is still old unused code - it will be cleaned in subsequent
PRs.

Integrate ubi-manifest [RHELDST-8706]

---

tests/test_ubipop.py
ubipop/__init__.py
ubipop/cli.py

This change adds compatibility with legacy code
that doesn't make use of ubi-manifest.
At this point --ubi-manifet-url cli option is optional,
and if provided, the new code paths using ubi-manifest will
be used.

Add compability for legacy code

---

tests/test_matcher.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_matcher.py
ubipop/ubi_manifest_client/models.py

- added missing nsvca property for ModulemdUnit model class
- added extra search for modulemd_defaults units
-- for association or unassociation actions they are diffed by profiles
so we need to get this info from pulp. Name or stream is not enough.

Fix handling modular units

---

tests/test_ubi_manifest_client.py
ubipop/ubi_manifest_client/models.py

Attribute version on ModulemdUnit class has to be stored as integer,
otherwise any queries on pulp will not work as expected.

Fixed ModulemdUnit model class

---

setup.py

It wasn't possible to import ubi_manifest_client package,
let's add proper lookup into setup.py in order to include
the package.

Fix packages lookup in setup.py

---

tests/integration/test_association.py

1.the returned pkg already be the list, so no need add [] to pass the parameter

Find the cause of the failed test cases and fix it [RHELDST-13188]

---

tests/test_ubipop.py
ubipop/__init__.py

If the debug or source repo for an RPM repo was not present, the returned value was None, which caused an attribute exception since the code would try accessing values from None. This change checks to ensure these repos actually exist, and raises an exception if they're not present.

Adding logs and exception for ubi repo sets [RHELDST-11863]

---

.github/workflows/tox-test.yml

The py2.7 stopped working for GH actions on the latest
ubuntu, let's use the older one where py27 still is offered.

Use specific ubuntu for py27 tests

---

tests/test_ubipop.py
ubipop/__init__.py

The main issue was resolved, in that we were trying to access a value which wasn't present. However, we should return None and allow the UbiRepoSet class to raise a RepoMissing exception,  which is already captured and logged.

Fixup: still dumps exception instead of simple log

---

requirements.txt

In the latest release of urllib3 there were some backwards incompatible changes released. Let's stick to urllib3 < 2 for the time being.
The affected code will likely be refactored or removed soon.

Use urllib3 < 2

---

.pylintrc
tests/test_cdn.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_cdn.py

This change adds functionality for purging CDN cache by ARLs.
- arguments required for purging CDN cache can be passed via
environment variables.
- publishing repositories and purging CDN cache was refactored
and encapsulated to `Publisher` class in order to have cleaner code
- TTL required for ARL generation is requested from CDN service. If live
data are not available, we fall back to default values.

Purge CDN cache by ARL [RHELDST-17152]

---

.github/workflows/docs.yml
.github/workflows/tox-test.yml
requirements.txt

The rpm-py-installer is no longer needed for this project, as the related code was moved to ubi-manifest project.
Let's drop the rpm-py-installer from requirements.txt now. Dropping also installation of rpm and other pkgs for CI.
This also fixes problems with rpm-py-installer installation on test environments.

Drop rpm-py-installer from requirements.txt

---

setup.py

1.Remove python2-specific entries in 'classifiers' 2.Specify minimal python version to 3.7

Retire python 2 support [RHELDST-15344]

---

tests/test_cli.py
tests/test_pulp.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_pulp_client.py
ubipop/cli.py

Adding support for PKI auth to pulp.
* Ubipop is now able to communicate with pulp also by using cert/key.
* Cert/key is possible to pass via CLI

Add PKI support for pulp auth [RHELDST-18033]

---

ubipop/__init__.py

Previously even if an empty string was used as ARL templates, it was enough to enable querying CDN headers. Let's now fix that, we query CDN only we have valid ARL templates.

Fix handling ARL templates

---

ubipop/_cdn.py

Previous usage of `f_map` caused creation of nested future and subsequent `result()` call didn't really wait for nested futures to finish. This caused immediate end of whole program before all submitted futures were started.
In production env likely only some of submitted cdn cache purges were allowed to start, some paths were not purged at all.
Let's now use `f_flat_map` instead which can be used with future-returning functions and any nesting of futures is automatically avoided - therefore the program will wait for all submitted cache purges.

Fix futures chaining

---

tests/test_cdn.py
tox.ini
ubipop/_cdn.py

Previously the TTL extraction was implemented in such way that it could potentially extract the wrong value, if the URL path contained a component that also matched the regex.
This commit changes the re.match() to re.search(), which ensures it will find the first occurrence of the match.
It also changes whitelist_externals to allowlist_externals in tox.ini

Fix TTL extraction [RHELDST-20510]

---

tests/test_cdn.py
ubipop/_cdn.py

ARL templates are extracted from environment variable which can in practice easily include some trailing whitespace characters. Unstripped ARLs with trailing whitechars are not accepted by the FastPurge API resulting in 4xx errors.

Sanitize provided ARL templates

---

ubipop/_cdn.py

Due to bug https://github.com/psf/requests/issues/3829, setting 'verify' on session doesn't work if REQUESTS_CA_BUNDLE is set on environment. The bundle defined via REQUESTS_CA_BUNDLE will take precedence and the custom bundle provided via 'verify' is ignored.
Let's now set 'verify' for each request.
This can be revetrted when the bug is fixed, likely in python-requests-v3.

Fix setting verify for requests

---

tests/test_ubipop.py
ubipop/__init__.py

After the rhel-ubi repos sync, this tool also took care of publishing the affected ubi repos to the CDN. However, this did not work for Exodus. It was decided that all publishes should be done via Pub, which is already configured and works for Exodus.
This commit prepares this tool for removal of publishing by making it possible to switch the publishing on/off as needed.
It also removes the intended deduplication of srpms in `_get_pulp_actions_src_pkgs()` which was a bit confusing and also unnecessary, since deduplication is done during manifest creation. Finally, it removes some forgotten unused variables and renames some variables so it's more understandable.

Make publishing of repos optional [RHELDST-21951]

---

requirements.txt

With recent changes:
* 8455d0ccdd87a7040b9b1d8dd063d59617216ae9 it is not required to use urllib<2.

Remove urllib<2 requirement

---

tests/test_cdn.py
tests/test_ubipop.py
ubipop/__init__.py
ubipop/_cdn.py

Exodus-gw is now responsible for Akamai CDN cache flush during publish in all the supported workflows. It makes the code for CDN cache flush obsolete. Hence, remove the code pertaining to CDN cache flush.

Retire obsolete Akamai cache purge support

---

tests/test_ubi_manifest_client.py
ubipop/ubi_manifest_client/client.py

The mutual_auth for kerberos was set as REQUIRED, but this was too demanding on auth. servers. Let's ease that a bit and set that as OPTIONAL.

Set mutual_auth as optional [RHELDST-24814]

---

poetry.lock

Update lock file with a separate PR, based on the recent pyproject.toml changes merged in PR #242, which caused conflict in PR #243. This PR is solely meant for rebasing.

Update lock file [RHELDST-25072]

---

tox.ini

Install poetry in system-wide with pip or pipx.

Fix usage of tox and poetry in ubi-population-tool [RHELDST-32220]
